filter:
    excluded_paths:
      - tests/*
      - vendor/*

tools:
    sensiolabs_security_checker: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
