language: php

php:
    - nightly
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - 5.6

matrix:
    allow_failures:
        - php: nightly

before_script:
    - composer self-update
    - composer install --prefer-source

script:
    - php vendor/bin/atoum
